services:
  webdav:
    build: .
    container_name: webdav
    hostname: webdav
    volumes:
      - ./data:/root/data
    command:
      - '--client-id=${CLIENT_ID}'
      - '--client-secret=${CLIENT_SECRET}'
      - '--token-file=/root/data/.gdrive-token'
    ports:
      - '8765:8765'
